#!/bin/bash
cd VM1
echo "Démarrage VM1\n"
vagrant up

cd ../VM2
echo "Démarrage VM2\n"
vagrant up

cd ../VM3
echo "Démarrage VM3\n"
vagrant up

cd ../VM1-6
echo "Démarrage VM1-6\n"
vagrant up

cd ../VM2-6
echo "Démarrage VM2-6\n"
vagrant up

cd ../VM3-6
echo "Démarrage VM3-6\n"
vagrant up
